<a href="https://colab.research.google.com/github/nova0035/MACHINE-LEARNING-PRACTICALS/blob/main/Practical-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical 2 :

- to convert a list of numeric values into a one-dimensional NumPy array

In [ ]:
import numpy as np

In [ ]:
numpy_array = np.array([1,2,3,4,5])

print(type(numpy_array),"\n",numpy_array)

<class 'numpy.ndarray'> 
 [1 2 3 4 5]


- to create a 3x3 matrix with values ranging from 2 to 10

In [ ]:
print(np.arange(2,11).reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


- Append Values At The End Of An Array

In [ ]:
print(np.append(numpy_array,[6,7]))

[1 2 3 4 5 6 7]


- to create another shape from an array without changing its data (3 x 2 to 2 x 3)

In [ ]:
array2 = np.array([[1,2],[3,4],[5,6]]).reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]
