<a href="https://colab.research.google.com/github/nova0035/MACHINE-LEARNING-PRACTICALS/blob/main/practical_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

practical - 4 : Write a NumPy program to implement following operation

In [1]:
import numpy as np

- to add, subtract, multiply, divide arguments element-wise
  - add


In [2]:
array = np.array([1,2,3,4,5,6])

print(np.add(array,2))

[3 4 5 6 7 8]



  - substraction

In [6]:
print(np.subtract(array,1))

[0 1 2 3 4 5]


- multiplication


In [7]:
print(np.multiply(array,5))

[ 5 10 15 20 25 30]


- division

In [9]:
array2 = [2,4,6,8,10]

print(np.divide(array2,2))

[1. 2. 3. 4. 5.]


-  to round elements of the array to the nearest integer

In [10]:
array3 = [1.2,4.5,34.1,45.6]

print(np.round(array3))

[ 1.  4. 34. 46.]


- to calculate mean across dimension, in a 2D numpy array

In [13]:
array4 = [[1,2,3],[4,5,6],[7,8,9]]

print(np.mean(array4,axis=0))
print(np.mean(array4,axis=1))

[4. 5. 6.]
[2. 5. 8.]


- to calculate the difference between neighboring elements, element-wise of a
given array

In [16]:
array5 = np.array([12,45,65,80,97,145])

print(np.diff(array5))

[33 20 15 17 48]
